// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW0Fs5xq5EhjWMHHmxXlbv5F5rOOPvSwc',
    appId: '1:447707683865:web:6f49a9de881c77b24d9e88',
    messagingSenderId: '447707683865',
    projectId: 'socialapp-ab3f9',
    authDomain: 'socialapp-ab3f9.firebaseapp.com',
    storageBucket: 'socialapp-ab3f9.firebasestorage.app',
    measurementId: 'G-9SZDX2PDQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmPdOSCthXp2m0IrrEY6CFGoiO9fjGyQA',
    appId: '1:447707683865:android:29e86e155f9b04a64d9e88',
    messagingSenderId: '447707683865',
    projectId: 'socialapp-ab3f9',
    storageBucket: 'socialapp-ab3f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2hJvQ9ByDPgUG-Mv_78cmkFlk82VJjKU',
    appId: '1:447707683865:ios:88c2166f7b5c768d4d9e88',
    messagingSenderId: '447707683865',
    projectId: 'socialapp-ab3f9',
    storageBucket: 'socialapp-ab3f9.firebasestorage.app',
    iosBundleId: 'com.example.social',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2hJvQ9ByDPgUG-Mv_78cmkFlk82VJjKU',
    appId: '1:447707683865:ios:88c2166f7b5c768d4d9e88',
    messagingSenderId: '447707683865',
    projectId: 'socialapp-ab3f9',
    storageBucket: 'socialapp-ab3f9.firebasestorage.app',
    iosBundleId: 'com.example.social',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW0Fs5xq5EhjWMHHmxXlbv5F5rOOPvSwc',
    appId: '1:447707683865:web:e0b6498d670f8b6b4d9e88',
    messagingSenderId: '447707683865',
    projectId: 'socialapp-ab3f9',
    authDomain: 'socialapp-ab3f9.firebaseapp.com',
    storageBucket: 'socialapp-ab3f9.firebasestorage.app',
    measurementId: 'G-0YJ92X4WRQ',
  );
}
